import Me from './resources/Me';
import Team from './resources/Team';
import Accounts from './resources/Accounts';
import Cadences from './resources/Cadences';
import CadenceMemberships from './resources/CadenceMemberships';
import Actions from './resources/Actions';
import ActionDetails from './resources/ActionDetails';
import People from './resources/People';
import Users from './resources/Users';
import Tags from './resources/Tags';
import TeamTemplates from './resources/TeamTemplates';
import Successes from './resources/Successes';
import Steps from './resources/Steps';
import Activities from './resources/Activities';
import CallDataRecords from './resources/CallDataRecords';
import CallDispositions from './resources/CallDispositions';
import Calls from './resources/Calls';
import CallSentiments from './resources/CallSentiments';
import CallerIDs from './resources/CallerIDs';
import CRMActivityFields from './resources/CRMActivityFields';
import CRMActivities from './resources/CRMActivities';
import CustomFields from './resources/CustomFields';
import Emails from './resources/Emails';
import EmailTemplates from './resources/EmailTemplates';
import Imports from './resources/Imports';
import LiveWebsiteTrackingParameters from './resources/LiveWebsiteTrackingParameters';
import Notes from './resources/Notes';
import OngoingActions from './resources/OngoingActions';
import PersonStages from './resources/PersonStages';
import RecordingSettings from './resources/RecordingSettings';

export default class SalesLoft {
  private readonly apiKey: string;
  public Me: Me;
  public Team: Team;
  public Accounts: Accounts;
  public Actions: Actions;
  public Activities: Activities;
  public Cadences: Cadences;
  public ActionDetails: ActionDetails;
  public CadenceMemberships: CadenceMemberships;
  public CallDataRecords: CallDataRecords;
  public CallDispositions: CallDispositions;
  public Calls: Calls;
  public CallSentiments: CallSentiments;
  public CallerIDs: CallerIDs;
  public CRMActivityFields: CRMActivityFields;
  public CRMActivities: CRMActivities;
  public CustomFields: CustomFields;
  public Emails: Emails;
  public EmailTemplates: EmailTemplates;
  public Imports: Imports;
  public LiveWebsiteTrackingParameters: LiveWebsiteTrackingParameters;
  public Notes: Notes;
  public OngoingActions: OngoingActions;
  public People: People;
  public PersonStages: PersonStages;
  public RecordingSettings: RecordingSettings;
  public Steps: Steps;
  public Successes: Successes;
  public Tags: Tags;
  public TeamTemplates: TeamTemplates;
  public Users: Users;

  constructor(apiKey:string) {
    this.apiKey = apiKey;
    this.Me = new Me('/me', this.apiKey);
    this.Team = new Team('/team', this.apiKey);
    this.Accounts = new Accounts('/accounts', this.apiKey);
    this.Actions = new Actions('/actions', this.apiKey);
    this.ActionDetails = new ActionDetails('/action_details', this.apiKey);
    this.Activities = new Activities('/activities', this.apiKey);
    this.Cadences = new Cadences('/cadences', this.apiKey);
    this.CadenceMemberships = new CadenceMemberships('/cadence_memberships', this.apiKey);
    this.CallDataRecords = new CallDataRecords('/call_data_records', this.apiKey);
    this.CallDispositions = new CallDispositions('/call_dispositions', this.apiKey);
    this.Calls = new Calls('/activities/calls', this.apiKey);
    this.CallSentiments = new CallSentiments('/call_sentiments', this.apiKey);
    this.CallerIDs = new CallerIDs('/phone_numbers/caller_ids', this.apiKey);
    this.CRMActivityFields = new CRMActivityFields('/crm_activity_fieldss' , this.apiKey);
    this.CRMActivities = new CRMActivities('/crm_activities', this.apiKey);
    this.CustomFields = new CustomFields('/custom_fields', this.apiKey);
    this.Emails = new Emails('/activities/emails', this.apiKey);
    this.EmailTemplates = new EmailTemplates('/email_templates', this.apiKey);
    this.Imports = new Imports('/imports', this.apiKey);
    this.LiveWebsiteTrackingParameters = new LiveWebsiteTrackingParameters('/live_website_tracking_parameters' , this.apiKey);
    this.Notes = new Notes('/notes', this.apiKey);
    this.OngoingActions = new OngoingActions('/ongoing_actions', this.apiKey);
    this.People = new People('/people', this.apiKey);
    this.PersonStages = new PersonStages('/person_stages', this.apiKey);
    this.RecordingSettings = new RecordingSettings('/recording_settings', this.apiKey);
    this.Steps = new Steps('/successes', this.apiKey);
    this.Successes = new Successes('/steps', this.apiKey);
    this.Tags = new Tags('/tags', this.apiKey);
    this.TeamTemplates = new TeamTemplates('/team_templates', this.apiKey);
    this.Users = new Users('/users', this.apiKey);
  }
  getApiKey() {
    return this.apiKey;
  }
}
